name: CI

on:
    push:
        branches:
            - CI
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"

            - run: npm ci

            - run: npm run build --if-present

            - run: npm test
            
            - name: Deploy react app to github pages
            uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1